steps:
  # Build my-app image
  - name: gcr.io/cloud_builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/my-app:$COMMIT_SHA
      - .

  # Push my-app image to Google Cloud Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/my-app:$COMMIT_SHA

  # Configure a kubeclt workspace for this project
  - name: gcr.io/cloud-builders/kubectl
    args:
      - cluster-info
    env:
      - CLOUDSDK_COMPUTE_REGION=$_CUSTOM_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$_CUSTOM_CLUSTER
      - KUBECONFIG=/workspace/.kube/config

  # Deploy with Helm
  - name: gcr.io/$PROJECT_ID/helm
    args:
      - upgrade
      - -i
      - my-app
      - ./kubernetes
      - --set
      - image.repository=gcr.io/$PROJECT_ID/my-app,image.tag=$COMMIT_SHA
      - -f
      - ./kubernetes/values.yaml
    env:
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=false
      - TILLER_NAMESPACE=kube-system
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args:
      - "-c"
      - |
          docker run --detach --name zap -u zap -v "$(pwd)/reports":/zap/reports/:rw   -i owasp/zap2docker-stable zap.sh -daemon -host 0.0.0.0 -port 8080   -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true   -config api.disablekey=true
          docker exec zap zap-cli --verbose quick-scan https://niveussolutions.com
          docker exec zap zap-cli --verbose report -o /zap/owasp-quick-scan-report.html --output-format html
timeout: 1200s
substitutions:
  _CUSTOM_REGION: asia-south1-a
  _CUSTOM_CLUSTER: zap
